services:
  app:
    build: .
    container_name: otp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - otp

  nginx:
    image: nginx:alpine
    container_name: otp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - otp

  postgres:
    image: postgres:16
    container_name: otp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - otp
  
  redis:
    image: redis:alpine
    container_name: otp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  node:
    image: node:20-alpine
    container_name: otp_node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: [ "sh", "-c", "npm install && npm run dev" ]
    networks:
      - otp

networks:
  otp:

volumes:
  pg_data:
